# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGekAklCJSusQjLBXWD4O-JLA5D9Omr0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity
import warnings

warnings.filterwarnings('ignore')

# --- Spotify Design System ---
SPOTIFY_GREEN = '#1DB954'
SPOTIFY_BLACK = '#191414'
SPOTIFY_WHITE = '#FFFFFF'
SPOTIFY_GRAY = '#535353'

# Set Seaborn Theme
sns.set_style("darkgrid", {"axes.facecolor": SPOTIFY_BLACK, "grid.color": SPOTIFY_GRAY, "figure.facecolor": SPOTIFY_BLACK, "text.color": SPOTIFY_WHITE, "axes.labelcolor": SPOTIFY_WHITE, "xtick.color": SPOTIFY_WHITE, "ytick.color": SPOTIFY_WHITE})
plt.rcParams['figure.facecolor'] = SPOTIFY_BLACK
plt.rcParams['axes.facecolor'] = SPOTIFY_BLACK
plt.rcParams['text.color'] = SPOTIFY_WHITE
plt.rcParams['axes.labelcolor'] = SPOTIFY_WHITE
plt.rcParams['xtick.color'] = SPOTIFY_WHITE
plt.rcParams['ytick.color'] = SPOTIFY_WHITE

# Plotly Template & Kaggle Setup
import plotly.io as pio
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True) # Required for Plotly in Kaggle

pio.templates["spotify_dark"] = go.layout.Template(
    layout=go.Layout(
        paper_bgcolor=SPOTIFY_BLACK,
        plot_bgcolor=SPOTIFY_BLACK,
        font={'color': SPOTIFY_WHITE},
        colorway=[SPOTIFY_GREEN, '#1ed760', '#ffffff', '#b3b3b3']
    )
)
pio.templates.default = "spotify_dark"

print("Setup Complete! Ready to rock. 🎸")

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Exemple : X et y
data = pd.DataFrame({
    "X": [1, 2, 3, 4, 5],
    "y": [2, 4, 5, 4, 5]
})

X = data[["X"]]
y = data["y"]

# Modèle
model = LinearRegression()
model.fit(X, y)

# Prédiction pour tracer la droite
X_range = np.linspace(X.min(), X.max(), 100).reshape(-1, 1)
y_pred = model.predict(X_range)

# Graphique
plt.scatter(X, y)
plt.plot(X_range, y_pred)
plt.xlabel("X")
plt.ylabel("y")
plt.title("Régression Linéaire")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import numpy as np

# Exemple : X et y binaire
data = pd.DataFrame({
    "X": [1, 2, 3, 4, 5, 6],
    "y": [0, 0, 0, 1, 1, 1]
})

X = data[["X"]]
y = data["y"]

# Modèle
model = LogisticRegression()
model.fit(X, y)

# Courbe logistique
X_range = np.linspace(X.min(), X.max(), 300).reshape(-1, 1)
y_prob = model.predict_proba(X_range)[:, 1]

# Graphique
plt.scatter(X, y)
plt.plot(X_range, y_prob)
plt.xlabel("X")
plt.ylabel("Probabilité")
plt.title("Régression Logistique")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Exemple : DataFrame
data = pd.DataFrame({
    "X": [1, 2, 3, 4, 5],
    "y": [2, 4, 5, 4, 5],
    "z": [5, 3, 4, 2, 1]
})

# Matrice de corrélation
corr = data.corr()
print(corr)

# Heatmap simple
plt.imshow(corr, interpolation='nearest')
plt.colorbar()
plt.xticks(range(len(corr.columns)), corr.columns)
plt.yticks(range(len(corr.columns)), corr.columns)
plt.title("Matrice de corrélation")
plt.show()