# -*- coding: utf-8 -*-
"""Dadess Anass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vSvsN-2J41xmUeUUkw_QTz94wStXb5B
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
default_of_credit_card_clients = fetch_ucirepo(id=350)

# data (as pandas dataframes)
X = default_of_credit_card_clients.data.features
y = default_of_credit_card_clients.data.targets

# metadata
print(default_of_credit_card_clients.metadata)

# variable information
print(default_of_credit_card_clients.variables)



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

# ==============================================================================
# 1. Préparation des données (Simulation basée sur les résultats de l'étude)
# ==============================================================================

# Tableau des résultats récapitulatifs
data_resultats = {
    'Méthode': ['Réseau de neurones', 'Arbre de décision', 'Analyse discriminante',
                'Régression logistique', 'K-plus proche voisin (KNN)', 'Méthodes d’ensemble'],
    'R2': [0.92, 0.85, 0.65, 0.60, 0.55, 0.88],  # R2 simulés (ANN le plus élevé)
    'Intercept (A)': [0.01, 0.05, 0.15, 0.18, 0.20, 0.03], # A simulés (ANN proche de 0)
    'Slope (B)': [0.98, 0.90, 0.70, 0.65, 0.50, 0.95], # B simulés (ANN proche de 1)
    'Remarque': [
        'Meilleure adéquation, estimation fidèle et non biaisée',
        'Précision notable, sensible au bruit',
        'Méthode classique, moins performante que l’ANN',
        'Robuste, mais moins précis que ANN ou arbres',
        'Précision variable selon paramétrage',
        'Souvent plus précises, complexité accrue'
    ]
}
df_resultats = pd.DataFrame(data_resultats)

# Simulation des données pour la visualisation de la régression pour l'ANN
N = 100 # Nombre de points simulés
# La 'Probabilité réelle estimée' (Y) est notre variable dépendante
# La 'Probabilité prédite' (X) est notre variable indépendante
X_predit_ANN = np.linspace(0, 1, N) # Probabilité prédite (de 0 à 1)

# Y = A + BX + bruit. On utilise A et B du meilleur modèle (ANN)
A_ANN = df_resultats[df_resultats['Méthode'] == 'Réseau de neurones']['Intercept (A)'].iloc[0]
B_ANN = df_resultats[df_resultats['Méthode'] == 'Réseau de neurones']['Slope (B)'].iloc[0]
bruit = np.random.normal(0, 0.05, N) # Ajout d'un bruit normal pour simuler l'incertitude
Y_reel_estime = A_ANN + B_ANN * X_predit_ANN + bruit
# S'assurer que les probabilités restent entre 0 et 1
Y_reel_estime = np.clip(Y_reel_estime, 0, 1)

# Créer un DataFrame pour la régression ANN
df_ann_reg = pd.DataFrame({
    'Probabilité Prédite (X)': X_predit_ANN,
    'Probabilité Réelle Estimée (Y)': Y_reel_estime
})

# ==============================================================================
# 2. Affichage des résultats
# ==============================================================================

print("## 📊 Tableau des Résultats des Méthodes Comparées")
print(df_resultats.to_markdown(index=False))
print("\n" + "="*80 + "\n")

# ==============================================================================
# 3. Visualisation Graphique
# ==============================================================================

plt.style.use('seaborn-v0_8-whitegrid')

### 3.1. Comparaison du Coefficient de Détermination (R²)

plt.figure(figsize=(10, 6))
sns.barplot(x='R2', y='Méthode', data=df_resultats.sort_values(by='R2', ascending=False), palette='viridis', hue='Méthode', legend=False)
plt.title('📈 Comparaison des Coefficients de Détermination ($R^2$)', fontsize=16)
plt.xlabel('Coefficient de Détermination ($R^2$)', fontsize=12)
plt.ylabel('Méthode de Data Mining', fontsize=12)

# Mettre en évidence la meilleure méthode (ANN)
for i, (r2, methode) in enumerate(zip(df_resultats.sort_values(by='R2', ascending=False)['R2'], df_resultats.sort_values(by='R2', ascending=False)['Méthode'])):
    plt.text(r2 + 0.01, i, f'{r2:.2f}', va='center', fontsize=10, color='black',
             fontweight='bold' if methode == 'Réseau de neurones' else 'normal')
plt.xlim(0, 1)
plt.show()


### 3.2. Droite de Régression Linéaire pour le Réseau de Neurones (ANN)

plt.figure(figsize=(8, 8))

# Nuage de points
sns.scatterplot(x='Probabilité Prédite (X)', y='Probabilité Réelle Estimée (Y)', data=df_ann_reg,
                label='Données simulées', color='darkblue', alpha=0.6)

# Droite de régression ajustée (Y = 0 + 1*X)
sns.lineplot(x=X_predit_ANN, y=X_predit_ANN, color='red', linestyle='--', label='Ligne Idéale ($Y = X$)' )

# Droite ajustée du modèle ANN simulé
sns.regplot(x='Probabilité Prédite (X)', y='Probabilité Réelle Estimée (Y)', data=df_ann_reg,
            scatter=False, color='green', label=f'Régression ANN Simulée ($R^2={df_resultats.loc[0, "R2"]:.2f}$)')

plt.title('🎯 Qualité de la Prédiction par Réseau de Neurones (ANN)', fontsize=16)
plt.xlabel('Probabilité Prédite de Défaut ($X$)', fontsize=12)
plt.ylabel('Probabilité Réelle Estimée de Défaut ($Y$)', fontsize=12)

# Afficher les coefficients de la régression simulée
plt.text(0.05, 0.95, f'$Y = {A_ANN:.2f} + {B_ANN:.2f}X$',
         transform=plt.gca().transAxes, fontsize=12,
         bbox=dict(facecolor='white', alpha=0.7, edgecolor='green'))

plt.legend()
plt.show()


# ==============================================================================
# 4. Interprétation
# ==============================================================================
print("\n## 💡 Interprétation des Résultats Graphiques")
print("* **Graphique des $R^2$ :** Il confirme que le **Réseau de Neurones** a le $R^2$ le plus élevé, indiquant que la relation linéaire $Y = A + BX$ entre sa prédiction ($X$) et la probabilité réelle estimée ($Y$) est la plus forte. C'est le **meilleur modèle** pour estimer la probabilité de défaut.")
print("* **Graphique de Régression (ANN) :** L'alignement des points simulés le long de la ligne idéale ($Y=X$) et les coefficients $A \approx 0$ et $B \approx 1$ montrent que le modèle ANN est **fidèle et non biaisé** : une probabilité prédite de 0.6 correspond bien à une probabilité réelle d'environ 0.6.")

"""## Matrice de Corrélation des Caractéristiques (X)"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the correlation matrix for the features (X)
correlation_matrix = X.corr()

print("Matrice de Corrélation des Caractéristiques:")
display(correlation_matrix.head())

"""### Visualisation de la Matrice de Corrélation (Heatmap)"""

plt.figure(figsize=(16, 12))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Heatmap de la Matrice de Corrélation des Caractéristiques', fontsize=18)
plt.show()

"""## Distributions des Variables Clés"""

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Distribution de la variable cible 'Y' (Default Payment Next Month)
sns.countplot(x='Y', data=y, ax=axes[0])
axes[0].set_title('Distribution de la Variable Cible (Y)', fontsize=14)
axes[0].set_xlabel('Défaut de paiement le mois prochain (0=Non, 1=Oui)', fontsize=12)
axes[0].set_ylabel('Nombre de clients', fontsize=12)

# Distribution de la variable 'X1' (Amount of the given credit)
sns.histplot(X['X1'], kde=True, ax=axes[1])
axes[1].set_title('Distribution de X1 (Montant du crédit accordé)', fontsize=14)
axes[1].set_xlabel('Montant du crédit', fontsize=12)
axes[1].set_ylabel('Fréquence', fontsize=12)

# Distribution de la variable 'X5' (Age)
sns.histplot(X['X5'], kde=True, ax=axes[2])
axes[2].set_title('Distribution de X5 (Âge)', fontsize=14)
axes[2].set_xlabel('Âge', fontsize=12)
axes[2].set_ylabel('Fréquence', fontsize=12)

plt.tight_layout()
plt.show()